CREATE TABLE projects (
    id               bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             varchar(200)  NOT NULL,
    description      text,
    status           varchar(20)   NOT NULL,
    llm_model_id     varchar(64)   NOT NULL,
    structured_input jsonb,
    created_at       timestamptz   NOT NULL,
    CONSTRAINT chk_projects_status CHECK (status IN ('READY', 'GENERATING', 'FAILED'))
);

CREATE INDEX idx_projects_created_at ON projects (created_at DESC);
